### ISSUE TITLE
希望可以提取邮件提醒的验证码

### ISSUE THREAD

**Issue by snailwind** [tianma8023/SmsCodeExtractor#1]
【邮件提醒189邮箱】
发件人:（618）226-2109
主题:收到来自(618)226-2109的新短信
正文:Yourconfirmationcodeis187964.Pleaseenteritinthetextfield.您的...
点击查看http://t.mail.189.cn/xxxxx
登录客户端，查看邮件更便捷:http://t.mail.189.cn/xx【回复t-1退订】

**Comment by tianma8023** [comment]
@snailwind 
- 如果这内容是短信内容的话，把验证码关键字加进去就行。
- 如果这是邮件内容的话，目前没办法解决，也不在这个App的考虑范围内。因为Android本身没有开放获取邮件内容的API。

**Comment by snailwind** [comment]
@tianma8023 
●这个是短信内容，运营商邮箱有短信提醒功能，将验证码邮件转发给运营商邮箱，可以间接实现短信接收邮件验证码。
●我试过了，以这条短信为例，识别出的是2109(发件人的号码的一部分)，看起来是因为中间有 "-" 这个符号，导致误判了。是否可以优化下识别逻辑，且关键字中无法做出排除。
●应该需要黑名单及识别优先级的功能来优化这个误判的问题。

**Comment by tianma8023** [comment]
@snailwind 
目前的App没有考虑到这种特殊的情况的处理方式，我会考虑下该作何处理。你目前可以这样解决，自定义验证码规则：
- 公司名：189邮箱
- 验证码关键字：confirmationcode
- 验证码正则：(?<![0-9])[0-9]{6}(?![0-9]) (通过快速选择按钮选取就好了)

**Comment by tianma8023** [comment]
@snailwind 
我仔细考虑了下，这个短信内容属于极少数情况，所以我这边目前就不再为了增强验证码识别算法的准确性而增加算法的复杂度了。采用我前面说的自定义规则方式，就可以解决当前问题了。
